image: gitpod/workspace-node-lts

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Start API
    init: |
      docker compose up -d db
      cd $GITPOD_REPO_ROOT/api && npm install      
    command: cd $GITPOD_REPO_ROOT/api && npm run watch
    env:
      MONGO_URL: mongodb://localhost:27017/movies
      NODE_ENV: development
  - name: Start web app
    init: cd $GITPOD_REPO_ROOT/app && npm install
    command: cd $GITPOD_REPO_ROOT/app && npm start
    env:
      NODE_ENV: development

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Web app
    description: Port 3000 for the frontend
    port: 3000
  - name: API
    description: Port 8888 for the API
    port: 8888
