version: "3"
services:
  api:
    environment:
      NODE_ENV: development
    entrypoint: npm run watch
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8888:8888"
  webserver:
    ports:
      - "8000:80"
