version: "3"
services:
  db:
    image: docker.io/mongo:6.0.6
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    environment:
      MONGO_URL: mongodb://db:27017/movies
    depends_on:
      - db
    ports:
      - "8888:8888"
  webserver:
    build: ./webserver
    depends_on:
      - api
    ports:
      - "8000:80"
volumes:
  mongo-data:
