version: "3"
services:
  db:
    image: mongo:6.0.6
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    environment:
      MONGO_URL: mongodb://db:27017/movies
    depends_on:
      - db
  webserver:
    build: ./webserver
    depends_on:
      - api
volumes:
  mongo-data:
